apiVersion: apps/v1
kind: Deployment
metadata: 
  name: javaapp
  namespace: dev
  labels: 
    app: java
spec: 
  minReadySeconds: 5
  replicas: 4
  selector: 
    matchLabels:
      app: javapods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:  
      labels:
        app: javapods
    spec:
      containers:
        - name: myjava-container
          image: 003364515214.dkr.ecr.ap-south-1.amazonaws.com/gaming/k8s:1.1
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
      resources:
        requests: 
          cpu: 125m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 128Mi
      restartPolicy: Always

          
            
            