apiVersion: apps/v1
kind: Deployment
metadata: 
  name: javaapp
  namespace: dev
  labels: 
    app: java
spec: 
  minReadySeconds: 5
  replicas: 5
  selector: 
    matchLabels:
      app: javapods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:  
      labels:
        app: java
    spec:
      containers:
        - name: my-container
          image: 003364515214.dkr.ecr.ap-south-1.amazonaws.com/gaming/k8s:1.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 90m
            limits:
              memory: 256Mi
              cpu: 150m
     
      
            