apiVersion: apps/v1
kind: Deployment
metadata: 
  name: java-app
  namespace: dev
  labels: 
    app: java
spec: 
  minReadySeconds: 5
  replicas: 5
  selector: 
    matchLabels:
      app: java
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:  
      labels:
        app: java
    spec:
      containers:
        - name: my-container
          image: mudasir102/java-repo:my-java
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 90m
            limits:
              memory: 28Mi
              cpu: 100m
     
      
            